from pathlib import Path

p=Path('src/NPVideoStudio.App/ViewModels/WorkspaceViewModel.cs')
s=p.read_text(encoding='utf-8')
old='''        item.RemoveCommand = new RelayCommand(() =>\n        {\n            // MediaAssetId is the persisted foreign key used by timeline clips. Removing an asset while\n            // a clip still references it makes the project internally invalid and the renderer later has\n            // no source file to resolve. Block that destructive state at the UI boundary instead.\n            var isUsedOnTimeline = Timeline.CurrentTracks\n                .SelectMany(track => track.Clips)\n                .Any(clip => string.Equals(clip.MediaAssetId, asset.Id, StringComparison.Ordinal));\n\n            if (isUsedOnTimeline)\n            {\n                StatusMessage = $"Medij „{asset.FileName}“ se koristi na vremenskoj traci. Prvo uklonite sve njegove klipove sa timeline-a, pa ga onda uklonite iz biblioteke.";\n                return;\n            }\n\n            Project.MediaLibrary.Remove(asset);\n            MediaLibrary.Remove(item);\n            StatusMessage = $"Medij „{asset.FileName}“ je uklonjen iz projekta.";\n        });'''
new='''        item.RemoveCommand = new AsyncRelayCommand(async () =>\n        {\n            // MediaAssetId is the persisted foreign key used by timeline clips. Removing an asset while\n            // a clip still references it makes the project internally invalid and the renderer later has\n            // no source file to resolve. Block that destructive state at the UI boundary instead.\n            var isUsedOnTimeline = Timeline.CurrentTracks\n                .SelectMany(track => track.Clips)\n                .Any(clip => string.Equals(clip.MediaAssetId, asset.Id, StringComparison.Ordinal));\n\n            if (isUsedOnTimeline)\n            {\n                StatusMessage = $"Medij „{asset.FileName}“ se koristi na vremenskoj traci. Prvo uklonite sve njegove klipove sa timeline-a, pa ga onda uklonite iz biblioteke.";\n                return;\n            }\n\n            DeleteOwnedProxyFile(asset);\n            Project.MediaLibrary.Remove(asset);\n            MediaLibrary.Remove(item);\n            if (!string.IsNullOrEmpty(Project.ProjectFilePath))\n            {\n                Timeline.SaveToProject();\n                await _projectRepository.SaveAsync(Project, Project.ProjectFilePath);\n            }\n            RefreshPreviewFrame(Player.CurrentTimeSeconds);\n            StatusMessage = $"Medij „{asset.FileName}“ i njegov NP Video Studio proxy su uklonjeni iz projekta.";\n        });'''
if old not in s: raise SystemExit('remove block anchor missing')
s=s.replace(old,new,1)
anchor='''    [RelayCommand]\n    private async Task ImportMediaAsync()'''
method='''    public static bool DeleteOwnedProxyFile(MediaAsset asset)\n    {\n        if (string.IsNullOrWhiteSpace(asset.ProxyFilePath)) return false;\n        try\n        {\n            var proxyPath = Path.GetFullPath(asset.ProxyFilePath);\n            var cacheRoot = Path.GetFullPath(AppSettings.ProxyCacheFolder()).TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar) + Path.DirectorySeparatorChar;\n            if (!proxyPath.StartsWith(cacheRoot, StringComparison.OrdinalIgnoreCase)) return false;\n            if (File.Exists(proxyPath)) File.Delete(proxyPath);\n            asset.ProxyFilePath = null;\n            asset.ProxyStatus = MediaProxyStatus.Original;\n            asset.ProxyError = null;\n            return true;\n        }\n        catch\n        {\n            return false;\n        }\n    }\n\n'''
if method.strip() not in s:
    if anchor not in s: raise SystemExit('method anchor missing')
    s=s.replace(anchor,method+anchor,1)
p.write_text(s,encoding='utf-8')

pt=Path('tests/NPVideoStudio.UnitTests/ProxyWorkspaceIntegrationTests.cs')
t=pt.read_text(encoding='utf-8')
insert='''\n    [AvaloniaFact]\n    public async Task RemovingUnusedMedia_DeletesOnlyOwnedProxyAndRemovesProjectEntry()\n    {\n        var source = Path.Combine(Path.GetTempPath(), $"npvs-proxy-remove-{Guid.NewGuid():N}.mp4");\n        File.WriteAllBytes(source, new byte[] { 1 });\n        var project = new Project { Name = "Proxy removal cleanup" };\n        var asset = new MediaAsset { FilePath = source, Kind = MediaKind.Video, HasVideoStream = true, HasAudioStream = true, Duration = TimeSpan.FromSeconds(2) };\n        project.MediaLibrary.Add(asset);\n        var proxy = new FakeProxyGeneratorService();\n        try\n        {\n            using var workspace = new WorkspaceViewModel(project, new FakeProjectRepository(), new FakeMediaProbeService(), new FakeStorageService(), new FakeFramePreviewService(), new FakeSubtitleGeneratorService(), new FakeRenderService(), new LoggerConfiguration().CreateLogger(), aiWorkerClient: null, proxyGeneratorService: proxy);\n            var item = Assert.Single(workspace.MediaLibrary);\n            await Assert.IsAssignableFrom<IAsyncRelayCommand>(item.GenerateProxyCommand).ExecuteAsync(null);\n            var generated = asset.ProxyFilePath!;\n            Assert.True(File.Exists(generated));\n\n            await Assert.IsAssignableFrom<IAsyncRelayCommand>(item.RemoveCommand).ExecuteAsync(null);\n\n            Assert.Empty(project.MediaLibrary);\n            Assert.Empty(workspace.MediaLibrary);\n            Assert.False(File.Exists(generated));\n        }\n        finally { File.Delete(source); }\n    }\n\n    [Fact]\n    public void DeleteOwnedProxyFile_NeverDeletesArbitraryExternalPath()\n    {\n        var external = Path.Combine(Path.GetTempPath(), $"npvs-external-{Guid.NewGuid():N}.mp4");\n        File.WriteAllBytes(external, new byte[] { 9 });\n        try\n        {\n            var asset = new MediaAsset { FilePath = "original.mp4", ProxyStatus = MediaProxyStatus.Ready, ProxyFilePath = external };\n            Assert.False(WorkspaceViewModel.DeleteOwnedProxyFile(asset));\n            Assert.True(File.Exists(external));\n            Assert.Equal(external, asset.ProxyFilePath);\n        }\n        finally { File.Delete(external); }\n    }\n'''
idx=t.rfind('\n}')
if idx<0: raise SystemExit('test class end missing')
if 'RemovingUnusedMedia_DeletesOnlyOwnedProxyAndRemovesProjectEntry' not in t:
    t=t[:idx]+insert+t[idx:]
pt.write_text(t,encoding='utf-8')
print('proxy cleanup materialized')